comidas = ['leite', 'couve','computador', 'tomate','garfo','faca','tablet','refrigerante']
bebidas = ['uva', 'colher','TV','vinho','cerveja','celular','banana']
talheres = ['arroz','iPhone', 'concha','whisky','vodka','feijão','colher de chá']
comidas.remove('leite')
comidas.remove('computador')
comidas.remove('garfo')
comidas.remove('faca')
comidas.remove('tablet')
comidas.remove('refrigerante')
bebidas.remove('uva')
bebidas.remove('colher')
bebidas.remove('TV')
bebidas.remove('celular')
bebidas.remove('banana')
talheres.remove('arroz')
talheres.remove('iPhone')
talheres.remove('whisky')
talheres.remove('vodka')
talheres.remove('feijão')
comidas.append('uva')
comidas.append('banana')
comidas.append('arroz')
comidas.append('feijão')
bebidas.append('whisky')
bebidas.append('leite')               
bebidas.append('refrigerante')           
bebidas.append('vodka')
talheres.append("colher")
talheres.append('garfo')
talheres.append('Faca')
eletronicos = []
eletronicos.append('computador')
eletronicos.append('tablet')
eletronicos.append('TV')
eletronicos.append('celular')
eletronicos.append('iPhone')
print(comidas)
print(bebidas)
print(talheres)
print(eletronicos)